import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { LenisScroller } from './scroll/lenis-scroller'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <title>Nordicaps</title>
      <meta name="description" content="Página para venta de gorras en Junin, Buenos Aires" />
      <body className={inter.className}>
        {children}
        <LenisScroller />
        </body>
    </html>
  )
}
